lhccong/fish-island-frontend

- src/components/AnnouncementModal/index.tsx
1. 修改 line 22 格式错误导致的错误跳转；
2. 优化格式，使代码结构更具可读性。
> fix(components): 修复公告内容中的 GitHub 链接格式错误导致无法正确跳转的问题

- config/routes.ts
- src/components/Game/ChessBoard.tsx
- src/components/Game/ChessPiece.tsx
- src/gameChineseChess.ts
- src/pages/Chat/index.tsx
- src/pages/Game/ChineseChess/index.css
- src/pages/Game/ChineseChess/index.less
- src/pages/Game/ChineseChess/index.tsx
- src/pages/Game/Piece/index.tsx
- src/services/websocket.ts
- src/utils/chineseChessLogic.ts
> feat: ✨ 添加中国象棋小游戏

- src/components/Game/ChessBoard.tsx
- src/pages/Game/ChineseChess/index.tsx
- src/utils/chineseChessLogic.ts
> feat: ✨ 中国象棋添加切换棋盘方向功能

- config/routes.ts
- src/pages/Utils/GitCommit/index.css
- src/pages/Utils/GitCommit/index.tsx
- src/pages/Utils/Translation/index.css
- src/pages/Utils/Translation/index.tsx
聚合翻译 ：聚合常用翻译网站、可自定义添加翻译网站
Git提交内容生成：一个 Git Commit Message 书写的表单工具，规范 Git 提交的Message
> feat: ✨ 工具栏添加聚合翻译和Git提交Message书写工具

- config/routes.ts
- src/app.tsx
- src/components/GlobalFloatingReader/index.tsx
- src/models/globalReader.ts
- src/pages/Reader/components/BookImport.tsx
- src/pages/Reader/components/BookReader.tsx
- src/pages/Reader/components/BookSearch.tsx
- src/pages/Reader/components/ChapterList.tsx
- src/pages/Reader/components/ReaderSettings.tsx
- src/pages/Reader/index.tsx
> feat: ✨ 添加摸鱼阅读（支持搜索小说、加入书架、悬浮阅读、隐蔽阅读等）

- src/pages/Game/GuessHero/index.tsx
- 新增最新英雄信息展示，页面加载时自动获取并显示最新英雄
- 优化页面布局，增加额外信息区域
> feat(Game/GuessHero): 添加游戏规则弹窗和最新英雄信息- 在页面中添加游戏规则弹窗，用户可点击"游戏规则"查看详细规则

- config/routes.ts
- src/pages/Game/GuessHero/index.css
- src/pages/Game/GuessHero/index.tsx
- 移除表格展示，改为列表展示猜测记录- 优化列表项样式，增加阴影、圆角等效果
- 添加最新英雄信息区块 -调整游戏规则弹窗样式
- 优化响应式布局，适配移动端
> refactor(Game): 重构 GuessHero 组件

- src/pages/Game/GuessHero/index.css
- src/pages/Game/GuessHero/index.tsx
- 修改列表项样式类名，增强代码可读性
- 调整列表项的内边距、外边距和圆角样式，提升视觉效果
> style(Game): 优化猜英雄列表项样式

- src/components/RightContent/AvatarDropdown.tsx
- src/pages/Chat/index.tsx
> 新增工作制大小周设置，修复工作制无法保存bug

- src/pages/Game/GuessHero/index.css
- src/pages/Game/GuessHero/index.tsx
- src/services/backend/heroController.ts
- src/services/backend/typings.d.ts
- 新增记录猜对英雄次数的 API 接口和相关逻辑
- 添加猜中人数的展示组件
- 实现登录后猜中次数计入统计的功能
- 优化游戏界面布局和样式
> feat(Game/GuessHero):增加猜中英雄次数统计功能

- package.json
- src/pages/Game/GuessHero/index.css
- src/pages/Game/GuessHero/index.tsx
- src/services/backend/heroController.ts
- src/services/backend/typings.d.ts
- src/utils/cryptoUtils.ts
- 在后端接口中添加 AES 加密的英雄数据
- 前端使用 crypto-js 库进行 AES 解密
- 更新 recordGuessSuccess 接口，添加英雄 ID 参数
- 优化游戏逻辑，确保只在解密成功后开始游戏
> feat(hero): 实现英雄数据 AES 加密传输

- src/pages/Game/GuessHero/index.tsx
- src/services/backend/typings.d.ts
- src/utils/cryptoUtils.ts
- 新增 cryptoUtils.ts 文件，实现 AES 加密和解密函数- 在 GuessHero 组件中集成 AES 解密功能，用于解密服务器返回的英雄数据
- 更新类型定义，使英雄数据在加密后以字符串形式传输
> feat(Game): 在猜英雄游戏中添加 AES 加密和解密

- src/pages/Game/2048/index.css
- src/pages/Game/ChineseChess/index.css
- src/pages/Game/Piece/index.css
- 整理和格式化 CSS 代码，提高可读性
- 添加响应式布局样式，提升不同屏幕尺寸下的用户体验
- 新增字体、颜色和间距等样式，增强页面视觉效果
> style(Game/2048): 优化 CSS 样式并增加响应式布局

- src/pages/Game/GuessHero/index.tsx
> 优化猜英雄排行榜显示效果

- src/pages/Game/GuessHero/index.css
- 在 GuessHero组件的样式文件中，为 background 的 height 属性添加 !important声明，确保高度设置优先级
> style(Game): 修复猜英雄页面背景高度

- src/pages/Index.tsx
- 实现移动端通过左右滑动切换数据源
- 优化切换逻辑：无论采用何种切换方式，均自动将滚动条重置至页面顶部
- 提升移动端用户在多数据源场景下的操作流畅性与浏览体验
> feat(Index): 在移动端添加左右滑动切换数据源功能

- src/pages/Chat/index.tsx
- 优化音乐搜索和选择界面，增加添加到歌单按钮
- 新增歌单相关状态和操作，包括加载、播放、添加和删除歌曲
> feat(Chat): 集成 APlayer 音乐播放器，支持歌单播放

- src/pages/Chat/index.tsx
> fix: 尝试处理摸鱼室在IOS15版本以下由于正则导致打不开的问题(需真机测试验证)

- src/components/RightContent/AvatarDropdown.tsx
- 在 AvatarDropdown 组件中的用户名输入框添加了提示信息- 提示用户每月只能修改一次用户名，并消耗 100积分
> feat(components): 添加用户名修改提示信息

- src/pages/Admin/User/index.tsx
- 在用户列表的删除按钮上增加了 Popconfirm 组件
- 弹出确认对话框以防止无意间删除用户
> feat(User): 为用户删除操作添加二次确认功能

- src/pages/Admin/Data/index.css
- src/pages/Admin/Data/index.tsx
- src/pages/Admin/User/index.tsx
- src/services/backend/typings.d.ts
- 修改数据展示页面布局和样式 -增加用户数据卡片点击功能，跳转到用户管理页面- 更新用户管理页面查询功能，支持注册时间和更新时间范围查询- 修改数据统计接口返回字段- 新增 index.css 文件，定义卡片样式
> refactor(admin): 重构用户数据展示和查询功能

- src/pages/Admin/User/index.tsx
- 在 createUser 和 updateUser 表单中的日期范围选择器中添加默认值
- 使用 moment.js 库将日期转换为正确格式 -改进用户体验，确保日期选择器在初始加载时显示正确的默认值
> fix(User): 修复用户管理页面日期选择器默认值问题

- src/pages/Admin/Data/index.tsx
- src/pages/Game/GuessHero/index.tsx
- src/services/backend/heroController.ts
- src/services/backend/index.ts
- src/services/backend/mockInterviewController.ts
- src/services/backend/typings.d.ts
- src/services/backend/userController.ts
- 重构了 heroController、userController 等后端接口，统一命名规范
- 更新了前端页面中的接口调用，以适应新的后端接口结构 -调整了部分数据结构和类型定义，以更好地匹配后端返回的数据
> refactor(backend): 重构后端接口并更新相关页面

- src/pages/Game/GuessHero/index.css
- 移除排行榜列表的 max-height 和 overflow-y 属性
- 调整领奖台项目高度，减少页面滚动条的影响
- 统一其他排名列表的样式，取消不必要的滚动条
- 优化响应式布局，调整相关 CSS 规则以适应不同屏幕尺寸
> style(Game): 优化猜英雄排行榜样式

- src/pages/Game/GuessHero/index.tsx
- 在排名 Modal 和规则 Modal 的底部添加"我知道了"按钮- 点击按钮后会关闭对应的 Modal 窗口
- 添加 e.stopPropagation() 以防止事件冒泡
> feat(Game/GuessHero): 为排名和规则 Modal 添加关闭按钮

- src/pages/Game/GuessHero/index.tsx
- src/pages/Post/index.tsx
- src/services/backend/typings.d.ts
- 在最新英雄信息中增加定位和种族两个属性的展示
- 使用 typeMap 映射英雄定位，若无对应映射则显示原始值
- 种族信息若为空，则显示为"无"
> feat(Game/GuessHero): 添加最新英雄的定位和种族信息

- src/pages/Post/index.tsx
- 添加最小宽度、高度、对齐方式和圆角样式
- 使序号展示更加美观和统一
> style(Post): 调整热门帖子序号样式

- src/pages/Chat/index.tsx
- src/pages/Draw/index.tsx
> 添加你画我猜邀请游戏功能

- config/config.ts
- config/defaultSettings.ts
- pnpm-lock.yaml
- src/app.tsx
- src/components/GlobalTitle/index.tsx
- src/components/LoginRegister/index.tsx
- src/components/RightContent/AvatarDropdown.tsx
- src/pages/User/Login/index.tsx
Reverts lhccong/fish-island-frontend#94
> Revert "fix: 修复摸鱼岛页面标题跟随菜单名称改变的问题"
